TaskManagerWeb/Controllers/TaskController.cs
using Microsoft.AspNetCore.Mvc;
using TaskManager.Data.Models;
namespace TaskManagerWeb.TaskController
{
    using Services;
    using TaskManager.Data.Models.Enums;

    public class TaskController : Controller
    {

        private readonly ITaskService _taskService;

        public TaskController(ITaskService taskService)
        {
            _taskService = taskService;
        }       

        public IActionResult Index()
        {
            var tasks = _taskService.GetAllTasks();

            return View(tasks);
        }

        //public IActionResult Create()
        //{
        //    return View();
        //}

        
        [HttpPost]
        public IActionResult CreateTask(TaskViewModel taskViewModel)
        {
            if (ModelState.IsValid)
            {
                var task = new Tasks
                {
                    
                    //Id = taskViewModel.Id,
                    Name = taskViewModel.Name,
                    Description = taskViewModel.Description,
                    DueDate = taskViewModel.DueDate,
                    Status = Status.inProgress,
                    PrioirtyLevel = taskViewModel.PrioirtyLevel,
                    
                    TaskListId = taskViewModel.TaskListId
                };

                _taskService.Create(task);

                return RedirectToAction("Details", "TaskList", new { id = task.TaskListId });
            }

            return View("AddTask", taskViewModel);
        }


        //[HttpPost]
        //[ValidateAntiForgeryToken]      
        //public IActionResult Create(Tasks task)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _taskService.Create(task);
        //        return RedirectToAction("Index");
        //    }
        //    return View(task);
        //}
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var item = _taskService.GetTaskById(id);

            var taskViewModel = new TaskViewModel
            {
                Id = item.Id,
                Name = item.Name,
                Description = item.Description,
                Status = item.Status,
                DueDate = item.DueDate,                
                TaskListId = item.TaskListId,

            };

            return View(taskViewModel);
        }
        [HttpPost]
        public IActionResult Edit(int id, TaskViewModel model)
        {
            var task = _taskService.GetTaskById(id);

            if (id != model.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                task.Name = model.Name;
                task.Description = model.Description;
                task.PrioirtyLevel = model.PrioirtyLevel;


                _taskService.Update(task);
                return RedirectToAction("Details","TaskList", new { id = model.TaskListId });
            }
            return View(task);
        }

        public IActionResult Delete(int id)
        {
            var task = _taskService.GetTaskById(id);
            if (task == null)
            {
                return NotFound();
            }
            return View(task);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var task = _taskService.GetTaskById(id);
            _taskService.Delete(id);

            return RedirectToAction("Details","TaskList", new { id = task.TaskListId });
        }

    }
}

TaskManagerWeb/Controllers/UsersController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using TaskManager.Data.Models;

using TaskManager.Data;
using System;

namespace TaskManagerWeb.Controllers
{
    

    public class UsersController : Controller
    {
        private readonly ManagerContext context;
        public UsersController(ManagerContext context)
        {
            this.context = context;
        }

        public  IActionResult Index()
        {
            IEnumerable<Users> users = context.Users;
            return View(users);
        }
        //GET
        public IActionResult Create()
        {
            return View();
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Users obj)
        {
            if ( obj.Username ==  obj.Name)
            {
                ModelState.AddModelError("name", "The Name cannot match the Username!");
            }
            if (ModelState.IsValid)
            {
                context.Users.Add(obj);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
             

        }
    }
}

TaskManagerWeb/Views/Shared/_Layout.cshtml
@using TaskManagerWeb.Verifications

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaskManagerWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TaskManagerWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
</head>
<body>
    <header>
        @if (Nav.isShowed)
        {
            
        
            <!-- Render the nav bar -->
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <div class="container-fluid">
                    <a class="navbar-brand" href="#">TaskManager</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarColor02">
                        <ul class="navbar-nav me-auto">
                            @*<li class="nav-item">
                        <a class="nav-link"  href="#">

                        <span class="visually-hidden">(current)</span>
                        </a>
                        <li/>*@

                           @* <li class="nav-item">
                                <a class="nav-link " asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link " asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link " asp-controller="Task" asp-action="Index">Task</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link " asp-controller="Users" asp-action="Index">Users</a>
                            </li>
                            *@
                            
                            <li class="nav-item">
                                <a class="nav-link " asp-controller="TaskList" asp-action="Index">TaskList</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link " asp-controller="Account" asp-action="LogOut">Log Out</a>
                            </li>
                            @*<li class="nav-item">
                                <a class="nav-link " asp-controller="Account" asp-action="SignUp">SignUp</a>
                            </li>*@
                            @*<li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                        <div class="dropdown-menu">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Separated link</a>
                        </div>
                        </li>*@
                        </ul>
                        <form class="d-flex">
                            <input class="form-control me-sm-2" type="search" placeholder="Search">
                            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                        </form>
                    </div>
                </div>
            </nav>
        }



    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted bg-dark">
        <div class="container">
            &copy; 2023 - TaskManagerWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>